tasks:
- install:
    # extra packages added for the rgw-d4ntests task
    extra_system_packages:
      deb: ['redis']
      rpm: ['redis']
- redis:
    client.0:
- thrashosds:
    timeout: 1200
    chance_pgnum_grow: 1
    chance_pgnum_shrink: 1
    chance_pgpnum_fix: 1
    op_delay: 30
    chance_test_min_size: 0
    ceph_objectstore_tool: false
