tasks:
- install:
    # extra packages added for the rgw-d4ntests task
    extra_system_packages:
      deb: ['redis']
      rpm: ['redis']
- ceph:
- redis:
    client.0:
- rgw: [client.0]
- workunit:
    clients:
      client.0:
        - rgw/s3_multipart_upload.pl
overrides:
  ceph:
    conf:
      client:
        rgw relaxed s3 bucket names: true
