tasks:
- install:
    # extra packages added for the rgw-d4ntests task
    extra_system_packages:
      deb: ['redis']
      rpm: ['redis']
- ceph: {cluster: c1}
- ceph: {cluster: c2}
- redis:
    c1.client.0:
    c2.client.0:
- rgw:
    c1.client.0:
      port: 8000
    c1.client.1:
      port: 8001
    c2.client.0:
      port: 8000
    c2.client.1:
      port: 8001
- rgw-multisite:
- rgw-multisite-tests:
    config:
      reconfigure_delay: 60
