tasks:
- install:
    # extra packages added for the rgw-d4ntests task
    extra_system_packages:
      deb: ['redis']
      rpm: ['redis']
- ceph:
- redis:
    client.0:
- dnsmasq:
    client.0:
      s3.: client.0
      s3-website.: client.1
- rgw:
    client.0:
      dns-name: s3.
    client.1:
      dns-s3website-name: s3-website.
- tox: [client.0]
- s3tests:
    client.0:
      rgw_server: client.0
      rgw_website_server: client.1
