tasks:
- install:
    # extra packages added for the rgw-d4ntests task
    extra_system_packages:
      deb: ['redis']
      rpm: ['redis']
- ceph:
- redis:
    client.0:
- rgw: [client.0]
- tox: [client.0]
- exec:
    client.0:
      - sudo chmod 0777 /var/lib/ceph
      - sudo chmod 0777 /var/lib/ceph/radosgw
      - sudo chmod 0777 /var/lib/ceph/radosgw/dbstore-default_ns.db
- s3tests:
    client.0:
      dbstore_tests: True
      rgw_server: client.0
      extra_attrs: ["not fails_on_dbstore"]
