tasks:
- install:
    # extra packages added for the rgw-d4ntests task
    extra_system_packages:
      deb: ['redis']
      rpm: ['redis']
- ceph:
- redis:
    client.0:
- rgw:
    client.0:
      port: 8000
- workunit:
    basedir: qa/workunits/rgw
    clients:
      client.0:
        - keystone-service-token.sh
