tasks:
- install:
    # extra packages added for the rgw-d4ntests task
    extra_system_packages:
      deb: ['redis']
      rpm: ['redis']
- ceph:
- redis:
    client.0:
- openssl_keys:
- rgw:
    client.0:

overrides:
  ceph:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
